language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: r4Koj3BoPRG6g2pOAC4q/MzDN8ZFSdp7VZg9kyfGI3GOaK0XPE3ipbQUyGL2yxROnJpXoS65T0upgaPuvuGX04FQN5gTrIjbXvUO4OHnYCAsXftYmqEhO004V28mFDjL308H2jhYDkTh1K4ZGvbR9bW9DCo4SUBxPwDAx0E0+rQSd4HJINxnW6V+SMkWhHk83ygPp/KH2bHQudCPfrD6MFnFSM0HaTVJ6B66USylBl1FkcqMLHX3yhyaMRYXcTi3qIEWOap7zQiox0w9FbLCjAcZBXGvAgTTBZ4v4DQ0/LW1/C+9wiY05Y0lW1Ro1d07cjThgiE/gaHbFzeYL6y3pcAjIEUvAUdylTCruXiahrz9zAwhfrw5BrGFZI/VNLRQ5sOo9XEzuy5aaGFK1wbsUxjFOUcTyKowzxUEK8wxsFlvEdrVlC/0Gid5yVNdvY5WQkA8gBZ+FJeacGtGyWrIbwM6IlPSQYQLrMjeBNhYUiD1pSQqA8Jgk9Qd6Rm3DnNIlYbJRUjcNbp8Z876IMyWngcYQ6fOQiKT/mgwrs7m4vC9vM4lxBoqFcIrarL2jqym0B16MPVFm271EpBti4l/CT/KLdA/S9ZTxBXjObwiR34qSbBhmzVYYfGVMkgHVw/ZbHMTRJsH23NE3sGjO4zwcNhzmdXVrTuAYGMCxeYI8Zo=
  app: whats-new-nick
  skip_cleanup: true
