language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: VR7RmGYbbSTDQswlDK8zW01RaeRaGdHBYAxqV8dkueOCITP5MAHxR1hgOQygtrO27jr7cWHh7U1HuLpuwgO+J5Egb0fd9hJ9e08k3CbE30biO9lpGLxuruuhpHRv3HEKNYm2mHGYU0CSbHExv3b2deV61mLqL0hEYpnWriJ7WBd+XZ8uJIDzsq9vW7SnkUCdto8o7we5YsvE1+lLFFwT5JlmFJldV2QWsdn4RUo+tRvtZiAf+nyRvkwIL3e5eMKlQLM8VmX9gso8jW5pLtR0jXO5xvEdIjQ+ArMFAKHdhq8tpuVuOaRXde/0MisyP96xkWh0HKWSdcOdRHefUGnajXC/cVD/W1IwosxP0Umrd5iVIE2h1gX3cFvz7Gf3fEgTUJSylBDHYBiin65tPJD5hLVmnq4EpPLb/n515819z2tBeJfAh1uiyzwtP+IqRsYKOThLWOTl6N7r6Gcw3QGA9+LvWttbwjoZRhOfdP+ZqYd5wC7zn9Fm47TYw5I7DzpkoiIv/vu86qfTDTIA0opeTt1p1MDvB/F9PtGk2ocXjWqJereTcEWpCnYrivRGXLg75AvCEh6VW0RaykjXqy9Xng6pNHBjq0Bc3PDf2PG5nLSjq7wyZoRX4+EK/8CgfvOYfoH5lVkbbkBVecjomdnwUSnA2bm/zIcGTaWL83iYaNw=
  app: whats-new-nick
  skip_cleanup: true
