language: node_js
node_js:
- node
notifications:
email: false
deploy:
  api_key:
    secure: SKzE+svJwHL/yyLTxVO061/1ExcOcnBdVKvBuk3jfcvbS3G6UIIlDDbL9SyRvOUemdjBLhLgBawsN7nDMJiOWXIlwjxoV4amUIMkpAmbqY00AwOW/zd62YtwEBL5srv2V/se+pLz+8RiQepJ7Wof52GnJgAkTHczN87qyblZhoeg4X4AYoUSX/23/nKPu26jN1hwR4HK6UOZSQFwIOm4uOzoEo1ht8PK0eMErw1u9pVn/NQUP6Zr9uuPH7TLIg4WyjqY1pEr6NH6XfT751mbQiZIKCWC7SMyKHyktYn+b4D6GGLvDiBIbEI/a6hs/2HNSmfYC4FI2VXhtVGRP/CobpGLzrLSZg7f1CQBSiXA5rJCz73Ovm4jGC+HzlIj7pQ6MEDMUUVSrdueWPcez8d4CEUx7k4lESg21u0/PvJKPV0e3TYvpG+3YncdTKfUHtw6bwdwnWjPv3gmCU91ETmm37Xrc0qxhNGSw+VzgQkE5E28DYMpbnZm3ddwCVRbqNYxjv+J9RQgH1HJMab9DpgsnpE0c5yHcwsK8FadjHnn5GIiPjQlRDH8pOXSVWAKkuJo/VLXmYwEXBu2xJwRAt6NEH+FC6sUYshOJi3xxnS1Eze3qvRI2eCz+0oaDM49vNWoqmV3ofeddwOLvwRWQQ4C+gdLdCfEHC7e3Np96MgIZjQ=
app: whats-new-nick
skip_cleanup: true
