language: node_js
node_js:
- node
notifications:
email: false
deploy:
  api_key:
    secure: RyhiRWfTERGWPIGKM876Q4wcpRFsGcG15OXrUUFdeEqHvezlXh9tE8/MwfV1NZcMchs5K5dWXy4VRW+owwVK8pdvyB7yIdLeE0hE1bs0mJZ85vCjhI5El+7RGh5OQufPxhcg27eD0n3Eldek7CKzBwKzeU1/2T10vEulbhZUeqpe/Bc0G6t47D6OGFfIiNgGMbmFkI3FtwrC9yQgYrRL/BKP1QAK+fdoJqCLLuFvNBg9dhhIw4S3OTKKTjur2not65ckJzvXAYAxe3bgVSTmVOLqgEDfuFelOFl0fz2CyJKqlY1jTLKsbQpYQJNagiJ8LLEyMSojV+V3pxeS5m+UndvPeU+YcWEDEPDqcGLrFLOmswDRLTVhv12vPI6O3KCyjXKQE3wWJhXjCdxmm7THEaJbL8C5WG6ZolfyJ+fPobCs4jTxgJpVRdFmmx7ZbJuu5+7mlN4bVVKo5BgMzcR4T5tM6QCStUhzQ51BTnk7XQ7UeTsvw4n8fv1dTUtBtqHCz7fw+FIJbpFUvU47n5P6zjPE7U0PxCP1jTjTiTpKyTsprXZI/hDttlygZsZBjmktGo8HYXLMSjARIRtX0lkf4DJvNQarGHhyqvM2shcfWJCkvtOxeurykUBYwYbQiVEdeGVKvHGKUNgtp//o4pVF89CiBfSlgG8GrAddXxE+mIQ=
  app: whats-new-nick
  skip_cleanup: true
